config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :vegetables
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :garden_types, except: [:destroy, :show]
  get 'sort_az', to: 'vegetables#sort_az'
  get 'sort_za', to: 'vegetables#sort_za'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden_type.rb
class GardenType < ApplicationRecord
  validates :name, uniqueness: true, presence: true, length: {minimum: 3, maximum: 25}
  has_many :vegetable_garden_types
  has_many :vegetables, through: :vegetable_garden_types
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :vegetables, dependent: :destroy
  validates :username, uniqueness: true, presence: true, length: {minimum: 3, maximum: 25}
  validates :password, presence: true, length: {minimum: 6, maximum: 25}
  validates :email, uniqueness: true, presence: true, format: {with: URI::MailTo::EMAIL_REGEXP}
end

app/models/vegetable.rb
class Vegetable < ApplicationRecord
    validates :name, presence:true, length: {minimum: 3, maximum: 50}
    validates :season, presence:true, length: {minimum: 3, maximum: 50}

    belongs_to :user
    has_many :vegetable_garden_types
    has_many :garden_types, through: :vegetable_garden_types
    
    default_scope { order(name: :desc) }
    scope :order_az, -> { reorder(name: :asc) }
    scope :order_za, -> { reorder(name: :desc) }
end

app/models/vegetable_garden_type.rb
class VegetableGardenType < ApplicationRecord
  belongs_to :vegetable
  belongs_to :garden_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to preform this action!"
      redirect_to login_path
    end
  end

end

app/controllers/garden_types_controller.rb
class GardenTypesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @garden_type = GardenType.new
  end
  
  def create
    @garden_type = GardenType.new(garden_type_params)
    if @garden_type.save
      flash[:notice] = "Garden type was successfully created!"
      redirect_to @garden_type
    else
      
      render 'new'
    end
  end

  def index
    @garden_types = GardenType.all
  end

  private

  def garden_type_params
    params.require(:garden_type).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can preform this action!"
      redirect_to garden_types_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        # redirect_to vegetables_path if logged_in?
    end
    def about

    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new

  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully!"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login information."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def show
    @veggies = @user.vegetables.paginate(page: params[:page], per_page: 3)
  end
  
  def index 
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated!"
      redirect_to vegetables_path
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Vegetable Garden #{@user.username}! You have successfully signed up"
      redirect_to vegetables_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
      session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and saved vegetables have been successfully deleted."
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end

end

app/controllers/vegetables_controller.rb
class VegetablesController < ApplicationController

  before_action :set_vegetable, only: [:show, :edit,:update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @veggies = Vegetable.paginate(page: params[:page], per_page: 5)
  end

  def new
     @veg = Vegetable.new
  end

  def create
    @veg = Vegetable.new(vegetable_params)
    @veg.user = current_user

    if @veg.save
      flash[:notice] = "Vegetable added!"
      redirect_to @veg
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @veg.update(vegetable_params)
      flash[:message] = "Vegetable details updated!"
      redirect_to @veg
    else 
      render 'edit'
    end
  end

  def destroy
    flash[:message] = "#{@veg.name} was successfully deleted!"
    @veg.destroy
    redirect_to vegetables_path
  end

  def sort_az
    @veggies = Vegetable.order_az.paginate(page: params[:page], per_page: 5)
    render 'index'
  end

  def sort_za
    @veggies = Vegetable.order_za.paginate(page: params[:page], per_page: 5)
    render 'index'
  end

  private

  def set_vegetable
    @veg = Vegetable.find(params[:id])
  end

  def vegetable_params
    params.require(:vegetable).permit(:name, :season, :conditions, garden_type_ids: [])
  end

  def require_same_user
    if current_user != @veg.user && !current_user.admin?
      flash[:alert] = "You can only edit your own vegetable"
      redirect_to @veg
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/views/garden_types/_garden_type.html.erb
<%= link_to garden_type.name, garden_types_path, class: "garden-type badge rounded-pill bg-success"%>

app/views/garden_types/index.html.erb
<div class="container-fluid yield-body">
  <h1 class="mt-4 yield-body-header">Vegetable Gardening Types:</h1>
  <hr>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 rounded garden-type-card">
          <h5 class="card-header">
              In Ground Gardens
          </h5>
          <div class="card-body">
          <%= image_tag "/assets/in_ground.jpg", class: "img-fluid rounded shadow" %>

            <p class="card-text">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore maiores excepturi vel velit, cumque nam atque magnam vitae expedita odio corporis natus debitis temporibus ipsam quo reiciendis. Architecto. <br><br>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo eos architecto atque exercitationem officia, cumque iste quam. Tempore nostrum repudiandae reprehenderit consequuntur obcaecati, nulla ab! Debitis quam, tenetur incidunt minima dignissimos natus facere facilis beatae rerum cumque, vel dolor commodi quis at ratione excepturi corporis vitae. Vel cum illo tempore alias molestias totam odio quibusdam unde! Inventore, earum.        
            </p>
          </div>
          <div class="card-footer text-muted">
            <div class="row mb-3">
              <div class="col-md-6">
                Links to resources: 
                <br>
                <br>
                <br>
                Blogs:
              </div>
              <div class="col-md-6">
                <a href="https://www.homedepot.com/b/Outdoors-Garden-Center/N-5yc1vZbx6k" class="resource-link">The Garden Center- Home Depot</a> <br>
                <a href="https://www.almanac.com/gardening-methods-overview" class="resource-link">The Farmer's Almanac</a> <br><br>
                <a href="https://bonnieplants.com/blogs/garden-fundamentals/how-to-plant-an-in-ground-garden-its-easy/" class="resource-link">Bonnie Plants</a> <br>
                <a href="https://growitbuildit.com/how-to-start-a-vegetable-garden-in-your-backyard/" class="resource-link">Grow it, Build it</a> <br>
              </div>
            </div>
          </div>
      </div>
        <div class="card text-center shadow mb-5 rounded garden-type-card">
          <h5 class="card-header">
              Raised Bed Garden
          </h5>
          <div class="card-body">
          <%= image_tag "/assets/raised_bed.jpg", class: "img-fluid rounded shadow" %>

            <p class="card-text">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore maiores excepturi vel velit, cumque nam atque magnam vitae expedita odio corporis natus debitis temporibus ipsam quo reiciendis. Architecto.<br><br>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo eos architecto atque exercitationem officia, cumque iste quam. Tempore nostrum repudiandae reprehenderit consequuntur obcaecati, nulla ab! Debitis quam, tenetur incidunt minima dignissimos natus facere facilis beatae rerum cumque, vel dolor commodi quis at ratione excepturi corporis vitae. Vel cum illo tempore alias molestias totam odio quibusdam unde! Inventore, earum.        
            </p>
          </div>
          <div class="card-footer text-muted">
            <div class="row mb-3">
              <div class="col-md-6">
                Links to resources: 
                <br>
                <br>
                <br>
                Blogs:
              </div>
              <div class="col-md-6">
                <a href="https://www.homedepot.com/b/Outdoors-Garden-Center/N-5yc1vZbx6k" class="resource-link">The Garden Center- Home Depot</a> <br>
                <a href="https://www.almanac.com/gardening-methods-overview" class="resource-link">The Farmer's Almanac</a> <br><br>
                <a href="https://bonnieplants.com/blogs/garden-fundamentals/how-to-plant-an-in-ground-garden-its-easy/" class="resource-link">Bonnie Plants</a> <br>
                <a href="https://growitbuildit.com/how-to-start-a-vegetable-garden-in-your-backyard/" class="resource-link">Grow it, Build it</a> <br>
              </div>
            </div>
          </div>
      </div>
              <div class="card text-center shadow mb-5 rounded garden-type-card">
          <h5 class="card-header">
              Container Gardening
          </h5>
          <div class="card-body">
          <%= image_tag "/assets/container.jpg", class: "img-fluid rounded shadow" %>
            <p class="card-text">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore maiores excepturi vel velit, cumque nam atque magnam vitae expedita odio corporis natus debitis temporibus ipsam quo reiciendis. Architecto. <br> <br>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo eos architecto atque exercitationem officia, cumque iste quam. Tempore nostrum repudiandae reprehenderit consequuntur obcaecati, nulla ab! Debitis quam, tenetur incidunt minima dignissimos natus facere facilis beatae rerum cumque, vel dolor commodi quis at ratione excepturi corporis vitae. Vel cum illo tempore alias molestias totam odio quibusdam unde! Inventore, earum.        
            </p>
          </div>
          <div class="card-footer text-muted">
            <div class="row mb-3">
              <div class="col-md-6">
                Links to resources: 
                <br>
                <br>
                <br>
                Blogs:
              </div>
              <div class="col-md-6">
                <a href="https://www.homedepot.com/b/Outdoors-Garden-Center/N-5yc1vZbx6k" class="resource-link">The Garden Center- Home Depot</a> <br>
                <a href="https://www.almanac.com/gardening-methods-overview" class="resource-link">The Farmer's Almanac</a> <br><br>
                <a href="https://bonnieplants.com/blogs/garden-fundamentals/how-to-plant-an-in-ground-garden-its-easy/" class="resource-link">Bonnie Plants</a> <br>
                <a href="https://growitbuildit.com/how-to-start-a-vegetable-garden-in-your-backyard/" class="resource-link">Grow it, Build it</a> <br>
              </div>
            </div>
          </div>
      </div>
        <div class="card text-center shadow mb-5 rounded garden-type-card">
          <h5 class="card-header">
              Trellising
          </h5>
          <div class="card-body">
          <%= image_tag "/assets/trellised.jpg", class: "img-fluid shadow rounded" %>

            <p class="card-text">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore maiores excepturi vel velit, cumque nam atque magnam vitae expedita odio corporis natus debitis temporibus ipsam quo reiciendis. Architecto. <br> <br>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo eos architecto atque exercitationem officia, cumque iste quam. Tempore nostrum repudiandae reprehenderit consequuntur obcaecati, nulla ab! Debitis quam, tenetur incidunt minima dignissimos natus facere facilis beatae rerum cumque, vel dolor commodi quis at ratione excepturi corporis vitae. Vel cum illo tempore alias molestias totam odio quibusdam unde! Inventore, earum.        
            </p>
          </div>
          <div class="card-footer text-muted">
            <div class="row mb-3">
              <div class="col-md-6">
                Links to resources: 
                <br>
                <br>
                <br>
                Blogs:
              </div>
              <div class="col-md-6">
                <a href="https://www.homedepot.com/b/Outdoors-Garden-Center/N-5yc1vZbx6k" class="resource-link">The Garden Center- Home Depot</a> <br>
                <a href="https://www.almanac.com/gardening-methods-overview" class="resource-link">The Farmer's Almanac</a> <br><br>
                <a href="https://bonnieplants.com/blogs/garden-fundamentals/how-to-plant-an-in-ground-garden-its-easy/" class="resource-link">Bonnie Plants</a> <br>
                <a href="https://growitbuildit.com/how-to-start-a-vegetable-garden-in-your-backyard/" class="resource-link">Grow it, Build it</a> <br>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>


<%# <% @garden_types.each do |type| %>
  <%# <div class="row justify-content-md-center"> %>
    <%# <div class="col-4 mt-4"> %>
      <%# <div class="card text-center shadow mb-5 rounded"> %>
        <%# <div class="card-body"> %>
          <%# <h5 class="card-title"> %>
            <%# <%= link_to type.name, garden_type_path(type), class: "text-success" %> 
          <%# </h5> %>
        <%# </div> %>
        <%# <div class="card-footer text-muted"> %>
          <%# <small>Created <%= time_ago_in_words(type.created_at) %>
            <%# edited <%= time_ago_in_words(type.created_at)   </small>  %>
        <%# </div> %>
      <%# </div> %>
    <%# </div> %>
  <%# </div> %>
<%# <% end %>  

app/views/garden_types/new.html.erb
<div class="container new-box">
  <h1 class="text-center mt-4">Create a New Garden Type</h1>
  
  <%# Errors template %>

<%= render 'shared/errors', obj: @garden_type %>

  <%# end error template %>

  <%= form_with(model: @garden_type) do |form| %>
    <div class="form-group pt-3">
      <%= form.label :name, "Garden Type:" %> 
      <%= form.text_field :name, class: "form-control", placeholder: "i.e. in ground, raised bed, etc" %>
    </div> 
    <br>
    <div class="text-center">
      <%= form.submit "Create Garden Type", class: "btn btn-success add-btn"%>
      <% end %>
      <%= link_to 'Cancel', vegetables_path, class: "btn btn-outline-success add-btn"%>
    </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container-fluid">
  <% flash.each do |name, message| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= message %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %> 
</div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
  <div class="container-fluid">

  <%# FIRST COLUMN %>
    <div class="col-lg-4">
      <%= link_to root_path do %>
        <i class="fas fa-carrot navbar-brand"></i>
      <% end %>
    </div>

    <%# SECOND COLUMN %>
    <div class="col-lg-4">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="nav-item p-2">
            <%= link_to "Gardeners", users_path, class: ["nav-link", ("active" if request.path == users_path)]%>
          </li>
          <li class="nav-item p-2">
            <%= link_to "Vegetables", vegetables_path, class: ["nav-link", ("active" if request.path == vegetables_path)]%>
            <hr class="info-line">
          </li>
          <li class="nav-item p-2">
            <%= link_to "Garden Types", garden_types_path, class: ["nav-link", ("active" if request.path == garden_types_path)]%>
          </li>
        </ul>
      </div>
    </div>

    <%# THIRD COLUMN %>
    <div class="col-lg-4 dropdown" >   
      <span class="user-border badge rounded-pill dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fas fa-user p-1"></i>
      </span>
      <ul class="dropdown-menu user-menu rounded shadow" aria-labelledby="dropdownMenuButton">
        <% if logged_in? %>
          <li class="dropdown-item">
            <em class="text-info"><%= "(admin)" if current_user.admin? %></em>
            <%= link_to current_user.username, user_path(current_user), class: "username"%>
          </li>
          <li class="nav-item"><%= link_to "Add Vegetable", new_vegetable_path, class:"dropdown-item" %></li>
          <% if logged_in? && current_user.admin? %>
            <li class="nav-item"><%= link_to "Add Garden Type", new_garden_type_path, class:"dropdown-item" %></li>
          <% end %>
          <li class="nav-item"><%= link_to "Log Out", logout_path, class:"dropdown-item", method: :delete %></li>            <li><hr class="dropdown-divider"></li>
          <li><%= link_to "Edit Profile", edit_user_path(current_user), class:"dropdown-item" %> </li>
          <li><%= link_to "Delete Profile", user_path(current_user), class:"dropdown-item delete-profile", method: :delete, data: { confirm: "Are you sure?"} %></li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Log In", login_path, class:"nav-link dropdown-item"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path, class:"nav-link dropdown-item"%>
          </li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veg Garden</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;600&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e988821a66.js" crossorigin="anonymous"></script>
  </head>

  <body>
 <%= render 'layouts/navigation'%>
  <%= render 'layouts/messages'%>
  <%= yield %>
  </body>
  <%= render 'layouts/footer'%>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/shared/_errors.html.erb
 <% if obj.errors.any? %> 
  <div class="container">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h4>The following errors prevented the <%= obj.class %> from being saved</h4>
      <ul>
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li> 
        <% end %> 
      </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %> 

app/views/shared/_form.html.erb
<%= form_with(model: @veg, url: new_vegetable_path) do |form| %>
  <%= form.label :name, "Vegetable Name:" %>
  <%= form.text_field :name %> 
  <br>
  <br>
  <%= form.label :season, "Growing Season:" %>
  <%= form.text_field :season %>
  <br>
  <br>
  <%= form.submit "Add Vegetable", class: "btn btn-success add-btn" %>
<% end %>

<%= link_to 'Cancel', vegetables_path, class: "btn btn-outline-success add-btn"%>

 <% if @veg.errors.any? %> 
  <% @veg.errors.full_messages.each do |message|%>
  <p><%= message %></p>
  <% end %>
<% end %>  

app/views/users/edit.html.erb
<div class="container-fluid new-box p-5">
  <h1 class="text-center mt-4">Edit your profile</h1>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container-fluid yield-body">

  <h1 class="mt-4 yield-body-header">All Local Vegetable Gardeners:</h1>
  <hr>

  <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>

  <div class="container-fluid">
    <% @users.each do |user| %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card user-card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              <%= link_to user.username, user %>
            </div>
            <div class="card-body">
              <h5 class="card-title">
                <%= link_to gravatar_for(user, size: 150), user %>
              </h5>
              <p class="card-text"><%= pluralize(user.vegetables.count, "vegetable") %></p>
              <%= link_to "View profile", user, class: "btn btn-outline-success" %>
              <% if logged_in? %> 
                <% if user == current_user %>
                  <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
                <% end %>
                <% if current_user.admin? %>
                  <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger",
                  method: :delete, data: {confirm: "Are you sure you want to delete this user and their vegetables?"}%>
                <% end %>
              <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container-fluid yield-body text-cetner">
  <div class="container-fluid new-box">
    <h1>Sign up to Vegetable Garden!</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid text-center user-profile">
  <h1 class="yield-body-header"><%= @user.username.capitalize %>'s Garden Profile</h1>
  <%= gravatar_for @user, size: 200 %>

  <div class="text-center mb-4 mt-4">
    <% if logged_in? && @user == current_user %>
      <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-success"%>
    <% end %>
  </div>
  <h3 class="text-center mt-4">Vegetables</h3>

  <div class="flickr_pagination">
    <%= will_paginate @veggies, :container => false %>
  </div>

  <%= render 'vegetables/vegetable'%>

  <div class="flickr_pagination">
    <%= will_paginate @veggies, :container => false %>
  </div>

</div>

app/views/vegetables/_vegetable.html.erb
<div class="col-lg-12">
<table class="table table-striped table-bordered">
  <thead>
    <tr>
    <th scope="col">
      <div class="dropdown">
        <a class="dropdown-toggle vegetable-name-header" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          Vegetable Name
        </a>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><%= link_to "Sort A-Z", sort_az_path, class:"dropdown-item" %></li>
          <li><%= link_to "Sort Z-A", sort_za_path, class: "dropdown-item"%></li>
        </ul>
      </div>
    </th>

      </th>
      <th scope="col">Growing Season</th>
      <th scope="col">Growing Condition</th>
      <th scope="col">Garden Type</th>
      <th scope="col">User</th>
      <% if logged_in? && current_user.admin? %>
        <th scope="col"></th>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @veggies.each do |veg|%>
    <tr>
      <td><%= link_to veg.name.capitalize, vegetable_path(veg), class: "link show-link"%></td>
      <td><%= veg.season.capitalize %></td>
      <td><%= veg.conditions? ? veg.conditions : "No growing conditions listed" %></td>
      <td>  
      <% if veg.garden_types.any? %>
        <%= render veg.garden_types %>
      <% end %></td>
      <td><%= veg.user.username if veg.user%></td>
      <% if logged_in? && current_user.admin? %>
       <td><%= link_to "Edit", edit_vegetable_path(veg), class: "link edit-link"%></td> 
       <td><%= link_to "Delete", vegetable_path(veg), method: :delete, class: "link delete-link"%></td> 
      <% end %> 
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Add New Vegetable", new_vegetable_path, class: "btn btn-outline new-button m-2"%>
</div>

app/views/vegetables/edit.html.erb
<div class="container new-box">
  <h1>Edit Vegetable Details</h1>

  <%= render 'form', obj: @veg %>
</div>

app/views/vegetables/new.html.erb
<div class="container new-box">
<h1>Add A Vegetable</h1>

<%= render 'form'%>
</div>

app/views/vegetables/show.html.erb
<div class="container-fluid yield-body">
  <div class="container-fluid new-box pb-5">
    <h1>Showing Vegetable Details</h1>
    <p><strong>Name: </strong> <%= @veg.name.capitalize %> </p>
    <p><strong>Growing Season: </strong> <%= @veg.season.capitalize %> </p>
    <p><strong>Growing Conditions: </strong> <%= @veg.conditions? ? @veg.conditions : "No growing conditions listed." %> </p>
    <% if @veg.garden_types.any? %>
      <p><em><%= render @veg.garden_types %></em></p>
    <% end %>
  <% if logged_in? && (@veg.user == current_user || current_user.admin?) %>
    <%= link_to 'Edit', edit_vegetable_path(@veg)%> |
    <%= link_to 'Delete', vegetable_path(@veg), method: :delete, data: {confirm: "Are you sure?"}%> |
  <% end %>
  <%= link_to 'Return to vegetables page', vegetables_path%>
  </div>
</div>